name: Go

on: [push]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo to Github Hosted VM
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Check Go version
        run: go version

      - name: Clean
        run: make clean

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Release and upload build file to assets
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          repo_token: "fake"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Auto release"
          files: |
            build/*