name: Go

on: [push]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo to Github Hosted VM
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        run: go version

      - name: Clean
        run: make clean

      - name: Test
        run: make test

      - name: Build
        run: make build